### ISSUE TITLE
Can't install @zodios/core from NPM

### ISSUE THREAD

**Issue by yanfaliupst** [ecyrbe/zodios-express#227]
```
479 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@zodios%2fcore - Not found
479 verbose stack     at /Users/yanfali/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
479 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
479 verbose stack     at async RegistryFetcher.packument (/Users/yanfa.li/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:92:19)
479 verbose stack     at async RegistryFetcher.manifest (/Users/yanfa.li/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:124:23)
479 verbose stack     at async RegistryFetcher.resolve (/Users/yanfa.li/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:57:5)
479 verbose stack     at async Arborist.[extractOrLink] (/Users/yanfa.li/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:683:7)
479 verbose stack     at async /Users/yanfa.li/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:608:7
480 verbose statusCode 404
481 verbose pkgid @zodios/core@10.9.0
482 verbose cwd /Users/yanfali/projects/backend
483 verbose Darwin 22.5.0
484 verbose node v16.19.1
485 verbose npm  v8.19.3
486 error code E404
487 error 404 Not Found - GET https://registry.npmjs.org/@zodios%2fcore - Not found
488 error 404
489 error 404  '@zodios/core@10.9.0' is not in this registry.
490 error 404
490 error 404 Note that you can also install from a
491 error 404 tarball, folder, http url, or git url.
492 verbose exit 1
```

**Comment by yanfaliupst** [comment]
The JSON file is gone from NPM. Both express and openapi are still there

**Comment by yanfaliupst** [comment]
```
❯ http -v https://registry.npmjs.org/@zodios/core
GET /@zodios/core HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: registry.npmjs.org
User-Agent: HTTPie/3.2.2



HTTP/1.1 404 Not Found
CF-RAY: 7e6c9169eae2eb3b-SEA
Connection: keep-alive
Content-Length: 21
Content-Type: application/json
Date: Fri, 14 Jul 2023 20:38:12 GMT
Server: cloudflare
Vary: Accept-Encoding

{
    "error": "Not found"
}
```

**Comment by yanfaliupst** [comment]
Not sure if this is an NPM outage, other random projects also appear to be failing

**Comment by yanfaliupst** [comment]
NPM was the issue. Sorry for reporting

**Comment by ecyrbe** [comment]
yes, there was an outage on npm, we usually can't remove a package from npm.
